from tableauhyperapi import SqlType

data = {
    'aged_payables_summary': [

        ("PayeeName", SqlType.text()),
        ("AmountPayable", SqlType.double()),
        ("NotYetDue", SqlType.double()),
        ("0To30", SqlType.double()),
        ("30To60", SqlType.double()),
        ("60To90", SqlType.double()),
        ("90Plus", SqlType.double()),
        ("Property", SqlType.text()),
        ("PropertyName", SqlType.text()),
        ("PropertyId", SqlType.int()),
        ("PropertyAddress", SqlType.text()),
        ("PropertyStreet1", SqlType.text()),
        ("PropertyStreet2", SqlType.text()),
        ("PropertyCity", SqlType.text()),
        ("PropertyState", SqlType.text()),
        ("PropertyZip", SqlType.text()),
        ("UnitId", SqlType.int()),
        ("30Plus", SqlType.double()),
        ("60Plus", SqlType.double()),
        ("InvoicePartyId", SqlType.text()),
        ("InvoicePartyType", SqlType.text()),

    ],

    'aged_receivables_detail': [

        ("PayerName", SqlType.text()),
        ("InvoiceOccurredOn", SqlType.date()),
        ("PostingDate", SqlType.date()),
        ("GlAccountNumber", SqlType.text()),
        ("GlAccountName", SqlType.text()),
        ("TotalAmount", SqlType.double()),
        ("AmountReceivable", SqlType.double()),
        ("0To30", SqlType.double()),
        ("30To60", SqlType.double()),
        ("60To90", SqlType.double()),
        ("90Plus", SqlType.double()),
        ("Property", SqlType.text()),
        ("PropertyName", SqlType.text()),
        ("PropertyId", SqlType.int()),
        ("PropertyAddress", SqlType.text()),
        ("PropertyStreet1", SqlType.text()),
        ("PropertyStreet2", SqlType.text()),
        ("PropertyCity", SqlType.text()),
        ("PropertyState", SqlType.text()),
        ("PropertyZip", SqlType.text()),
        ("GlAccountId", SqlType.int()),
        ("FutureCharges", SqlType.double()),
        ("30Plus", SqlType.double()),
        ("60Plus", SqlType.double()),
        ("OccupancyName", SqlType.text()),
        ("GlAccount", SqlType.text()),
        ("UnitAddress", SqlType.text()),
        ("UnitStreet1", SqlType.text()),
        ("UnitStreet2", SqlType.text()),
        ("UnitCity", SqlType.text()),
        ("UnitState", SqlType.text()),
        ("UnitZip", SqlType.text()),
        ("UnitName", SqlType.text()),
        ("UnitType", SqlType.text()),
        ("UnitTags", SqlType.text()),
        ("TenantStatus", SqlType.text()),
        ("PaymentPlan", SqlType.text()),
        ("occupancy_id", SqlType.int()),
        ("UnitId", SqlType.int()),
    ],

    'bill_detail': [
        ("ReferenceNumber", SqlType.text()),
        ("BillDate", SqlType.date()),
        ("DueDate", SqlType.date()),
        ("Account", SqlType.text()),
        ("Property", SqlType.text()),

        ("Unit", SqlType.text()),
        ("PayeeName", SqlType.text()),
        ("Paid", SqlType.double()),
        ("Unpaid", SqlType.double()),
        ("CheckNumber", SqlType.text()),
        ("PaymentDate", SqlType.date()),

        ("Description", SqlType.text()),
        ("PostingDate", SqlType.date()),
        ("AccountName", SqlType.text()),
        ("AccountNumber", SqlType.text()),
        ("PropertyName", SqlType.text()),

        ("PropertyId", SqlType.int()),
        ("PropertyAddress", SqlType.text()),
        ("PropertyStreet", SqlType.text()),
        ("PropertyStreet2", SqlType.text()),
        ("PropertyCity", SqlType.text()),
        ("PropertyState", SqlType.text()),

        ('PropertyZip', SqlType.text()),
        ('WorkOrder', SqlType.text()),
        ("CashAccount", SqlType.text()),
        ('TxnId', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('Quantity', SqlType.double()),

        ('Rate', SqlType.double()),
        ('WorkOrderAssignee', SqlType.text()),
        ('ApprovalStatus', SqlType.text()),
        ('LastApprover', SqlType.text()),
        ('NextApprovers', SqlType.text()),
        ('DaysPendingApproval', SqlType.text()),

        ('BoardApprovalStatus', SqlType.text()),
        ('TxnCreatedAt', SqlType.date()),
        ('TxnUpdatedAt', SqlType.date()),
        ('CreatedBy', SqlType.text()),
        ("BankAccount", SqlType.text()),
        ("OtherPaymentType", SqlType.text()),

        ("PurchaseOrderNumber", SqlType.text()),
        ("PurchaseOrderId", SqlType.int()),
        ("ProjectId", SqlType.int()),
        ("ServiceRequestId", SqlType.int()),
        ("VendorId", SqlType.int()),

    ],

    'cancelled_processes': [
        ('AttachableFor', SqlType.text()),
        ('Property', SqlType.text()),
        ('WorkflowName', SqlType.text()),
        ('CancelledDate', SqlType.text()),
        ('CancelledBy', SqlType.text()),
        ('CancellationReason', SqlType.text()),
    ],

    'charge_detail': [

        ('ChargeDate', SqlType.date()),
        ('ReceiptInfo', SqlType.text()),
        ('GlAccountNumber', SqlType.text()),
        ('GlAccountName', SqlType.text()),
        ('ChargedTo', SqlType.text()),
        ('ChargeAmount', SqlType.double()),
        ('PaidAmount', SqlType.double()),
        ('Unit', SqlType.text()),
        ('UnitAddress', SqlType.text()),
        ('UnitStreet1', SqlType.text()),
        ('UnitStreet2', SqlType.text()),
        ('UnitCity', SqlType.text()),
        ('UnitState', SqlType.text()),
        ('UnitZip', SqlType.text()),
        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('TxnId', SqlType.int()),
        ('PartyId', SqlType.int()),
        ('Owners', SqlType.text()),
        ('PostingDate', SqlType.date()),
        ('UnitID', SqlType.int()),
        ('ReceivedFromID', SqlType.int()),
        ('GlAccountId', SqlType.int()),
    ],

    'chart_of_accounts': [
        ('GlAccountNumber', SqlType.text()),
        ('GlAccountName', SqlType.text()),
        ('GlAccountType', SqlType.text()),  # confusion
        ('SubAccountof', SqlType.text()),
        ('OffsetAccount', SqlType.text()),
        ('Options', SqlType.text()),  # confusion
        ('Hidden', SqlType.text()),
        ('SubjectToTaxAuthority', SqlType.text()),  # confusion
        ('FundAccount', SqlType.text()),
        ('GlAccountId', SqlType.int()),
        ('SubAccountOfId', SqlType.int()),
        ('OffsetAccountId', SqlType.int()),

    ],

    'check_register_detail': [

        ('BankAccount', SqlType.text()),
        ('PayeeName', SqlType.text()),
        ('CheckNumber', SqlType.text()),
        ('Cleared', SqlType.text()),  # confusion
        ('CheckMemo', SqlType.text()),
        ('OccurredDate', SqlType.date()),
        ('PaymentAmount', SqlType.double()),
        ('PropertyName', SqlType.text()),
        ('GLAccountNumber', SqlType.text()),
        ('GlAccountName', SqlType.text()),
        ('InvoiceAmount', SqlType.double()),
        ('Remarks', SqlType.text()),
        ('Reference', SqlType.text()),
        ('ACHBatchGenDate', SqlType.date()),
        ('PropertyAddress', SqlType.text()),
        ('GLAccountId', SqlType.int()),
        ('PropertyId', SqlType.int()),

    ],

    'completed_processes': [
        ('AttachableFor', SqlType.text()),
        ('Property', SqlType.text()),
        ('WorkflowName', SqlType.text()),
        ('CompletedDate', SqlType.text()),

    ],

    'delinquency': [

        ('Unit', SqlType.text()),
        ('Name', SqlType.text()),
        ('TenantStatus', SqlType.text()),
        ('Tags', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('MoveIn', SqlType.date()),
        ('MoveOut', SqlType.date()),
        ('Deposit', SqlType.double()),
        ('AmountReceivable', SqlType.double()),
        ('DelinquentSubsidyAmount', SqlType.double()),
        ('0To30', SqlType.double()),
        ('30Plus', SqlType.double()),
        ('LastPayment', SqlType.date()),
        ('PaymentAmount', SqlType.double()),
        ('LateCount', SqlType.int()),
        ('PrimaryTenantEmail', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('NotYetDue', SqlType.double()),
        ('30To60', SqlType.double()),
        ('60Plus', SqlType.double()),
        ('60To90', SqlType.double()),
        ('90Plus', SqlType.double()),
        ('PrepaymentAmount', SqlType.double()),
        ('NSF', SqlType.int()),
        ('CertifiedFundsOnly', SqlType.text()),  # confusion
        ('Rent', SqlType.double()),
        ('DelinquentRent', SqlType.double()),
        ('DelinquencyNotes', SqlType.text()),
        ('MonthlyCharges', SqlType.text()),
        ('RentDueDay', SqlType.int()),
        ('InCollections', SqlType.text()),
        ('CollectionsAgency', SqlType.text()),
        ('UnitId', SqlType.int()),
        ('OccupancyId', SqlType.int()),
        ('PaymentPlan', SqlType.double()),

    ],

    'deposit_register': [

        ('DepositNumber', SqlType.text()),
        ('ReceiptDate', SqlType.date()),
        ('Payer', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('Type', SqlType.text()),
        ('Reference', SqlType.text()),
        ('Description', SqlType.text()),
        ('DepositAmount', SqlType.double()),
        ('ReceiptAmount', SqlType.double()),
        ('Cleared', SqlType.text()),  # confusion
        ('ReceiptDescription', SqlType.text()),
        ('UnitName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('UnitId', SqlType.int()),

    ],

    'general_ledger': [

        ('Property', SqlType.text()),
        ('PostDate', SqlType.date()),
        ('PartyName', SqlType.text()),
        ('Type', SqlType.text()),
        ('Reference', SqlType.text()),
        ('Debit', SqlType.double()),
        ('Credit', SqlType.double()),
        ('Balance', SqlType.double()),
        ('Description', SqlType.text()),
        ('GlAccountName', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('Unit', SqlType.text()),
        ('Month', SqlType.text()),
        ('Quarter', SqlType.text()),
        ('Year', SqlType.text()),
        ('BankAccount', SqlType.text()),
        ('TxnCreatedAt', SqlType.date()),
        ('TxnUpdatedAt', SqlType.date()),
        ('CreatedBy', SqlType.text()),
        ('Remarks', SqlType.text()),
        ('DepositDate', SqlType.date()),
        ('DepositNumber', SqlType.text()),
        ('CashAccount', SqlType.text()),
        ('PartyId', SqlType.int()),
        ('TxnId', SqlType.int()),
        ('TxnDetailId', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('GlAccountId', SqlType.int()),

    ],

    'gross_potential_rent_enhanced': [

        ('Unit', SqlType.text()),
        ('BdBa', SqlType.text()),
        ('Tenant', SqlType.text()),
        ('GrossPotentialRent', SqlType.double()),
        ('LossToMarket', SqlType.double()),
        ('MonthlyRent', SqlType.double()),
        ('Concessions', SqlType.double()),
        ('VacancyLoss', SqlType.double()),
        ('ModelLoss', SqlType.double()),
        ('RenovationLoss', SqlType.double()),
        ('OfficeLoss', SqlType.double()),
        ('DelinquencyLoss', SqlType.double()),
        ('NetRentIncome', SqlType.double()),
        ('Period', SqlType.text()),
        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.text()),
        ('PropertyAddress', SqlType.int()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('UnitTags', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('OccupancyId', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('MarketRent', SqlType.double()),
        ('RentCharges', SqlType.double()),

    ],
    'guest_cards': [
        ('RentCharges', SqlType.text()),
        ('Name', SqlType.text()),
        ('EmailAddress', SqlType.text()),
        ('PhoneNumber', SqlType.text()),
        ('Received', SqlType.date()),
        ('LastActivityDate', SqlType.date()),
        ('LastActivityType', SqlType.text()),
        ('Status', SqlType.text()),
        ('MoveInPreference', SqlType.date()),
        ('MaxRent', SqlType.double()),
        ('BedBathPreference', SqlType.text()),
        ('PetPreference', SqlType.text()),
        ('MonthlyIncome', SqlType.double()),
        ('CreditScore', SqlType.text()),
        ('LeadType', SqlType.text()),
        ('Source', SqlType.text()),
        ('Property', SqlType.text()),
        ('Unit', SqlType.text()),
        ('AssignedUser', SqlType.text()),
        ('AssignedUserID', SqlType.int()),
        ('GuestCardId', SqlType.int()),
        ('PropertyId', SqlType.text()),
        ('UnitId', SqlType.int()),
        ('Notes', SqlType.text()),
        ('TenantId', SqlType.text()),

    ],

    'homeowner_directory': [
        ('Property', SqlType.text()),
        ('Unit', SqlType.text()),
        ('Homeowner', SqlType.text()),
        ('ElectronicDeliveryConsent', SqlType.text()),  # confusion
        ('Status', SqlType.text()),
        ('RenterOccupiedUnit', SqlType.text()),  # confusion
        ('HomeownerType', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('Emails', SqlType.text()),
        ('LockboxId', SqlType.text()),
        ('OwnershipPercentage', SqlType.text()),
        ('Dues', SqlType.double()),
        ('Tags', SqlType.text()),
        ('HomeownerAddress', SqlType.text()),
        ('HomeownerStreet1', SqlType.text()),
        ('HomeownerStreet2', SqlType.text()),
        ('HomeownerCity', SqlType.text()),
        ('HomeownerState', SqlType.text()),
        ('HomeownerZip', SqlType.text()),
        ('HomeownerCountry', SqlType.text()),
        ('HomeownerBirthdate', SqlType.text()),
        ('UnitAddress', SqlType.text()),
        ('UnitStreet1', SqlType.text()),
        ('UnitStreet2', SqlType.text()),
        ('UnitCity', SqlType.text()),
        ('UnitState', SqlType.text()),
        ('UnitZip', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('FirstName', SqlType.text()),
        ('LastName', SqlType.text()),
        ('CertifiedFundsOnly', SqlType.text()),# confusion
        ('EligibleForDuesIncrease', SqlType.date()),
        ('LastDuesIncrease', SqlType.date()),
        ('NextDuesAdjustment', SqlType.date()),
        ('OnlinePortalActivated', SqlType.text()),# confusion
        ('OnlinePaymentsRecurringTotal', SqlType.text()),
        ('OnlinePaymentsRecurringCount', SqlType.text()),
        ('OnlinePortalLogin', SqlType.text()),
        ('SendDuesReminders', SqlType.text()),# confusion
        ('UnitTags', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('LateFeeType', SqlType.text()),
        ('LateFeeBaseAmount', SqlType.double()),
        ('LateFeeDailyAmount', SqlType.double()),
        ('DuesGraceDays', SqlType.int()),
        ('DuesGraceDayFixedDay', SqlType.int()),
        ('LateFeeGraceBalance', SqlType.double()),
        ('MaxDailyLateFeesAmount', SqlType.double()),
        ('IgnorePartialPayments', SqlType.text()),
        ('PurchaseDate', SqlType.date()),
        ('SaleDate', SqlType.date()),
        ('InsuranceCompanyName', SqlType.text()),
        ('InsuranceExpiration', SqlType.text()),
        ('InsurancePolicyNumber', SqlType.text()),
        ('LicensePlates', SqlType.text()),
        ('Pets', SqlType.text()),
        ('RenterLeaseStartDate', SqlType.date()),
        ('RenterLeaseEndDate', SqlType.date()),
        ('NsfFee', SqlType.double()),
        ('RequireOnlinePaymentsInFull', SqlType.text()),# confusiob
        ('SelectedHomeownerId', SqlType.int()),
        ('OccupancyId', SqlType.int()),
        ('UnitId', SqlType.int()),
    ],

    'homeowner_vehicle_info': [

        ('Property', SqlType.text()),
        ('Unit', SqlType.text()),
        ('Homeowner', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('HomeownerStatus', SqlType.text()),
        ('Make', SqlType.text()),
        ('Model', SqlType.text()),
        ('Color', SqlType.text()),
        ('LicensePlate', SqlType.text()),
        ('Year', SqlType.text()),
        ('PermitNumber', SqlType.text()),
        ('UnitId', SqlType.int()),
        ('PropertyId', SqlType.int()),
        ('OccupancyId', SqlType.int()),
        ('HomeownerId', SqlType.int()),
        ('RentableItem', SqlType.text()),
    ],

    'in_progress_workflows': [

        ('AttachableFor', SqlType.text()),
        ('Property', SqlType.text()),
        ('WorkflowName', SqlType.text()),
        ('CurrentStep', SqlType.text()),
        ('Status', SqlType.text()),
        ('DueDate', SqlType.text()),
        ('AssignedTo', SqlType.text()),
    ],

    'lease_expiration_detail': [

        ('Property', SqlType.text()),
        ('Unit', SqlType.text()),
        ('UnitTags', SqlType.text()),
        ('MoveIn', SqlType.date()),
        ('LeaseExpires', SqlType.date()),
        ('MarketRent', SqlType.double()),
        ('Sqft', SqlType.int()),
        ('TenantName', SqlType.text()),

        ('Deposit', SqlType.double()),
        ('Rent', SqlType.double()),
        ('PhoneNumbers', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),

        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('LeaseExpiresMonth', SqlType.text()),

        ('UnitId', SqlType.int()),
        ('OccupancyId', SqlType.int()),
        ('OwnerAgent', SqlType.text()),
        ('RentStatus', SqlType.text()),
        ('LegalRent', SqlType.double()),
        ('Owners', SqlType.text()),
        ('LastRentIncrease', SqlType.date()),
        ('NextRentAdjustment', SqlType.date()),
        ('NextRentIncrease', SqlType.date()),
        ('LeaseSignDate', SqlType.date()),
        ('LastLeaseRenewal', SqlType.date()),
        ('Status', SqlType.text()),
        ('RenewalStartDate', SqlType.date()),
        ('NoticeGivenDate', SqlType.date()),
        ('MoveOut', SqlType.date()),
        ('TenantTags', SqlType.text()),
        ('ComputedMarketRent', SqlType.double()),

    ],

    'payment_plans': [
        ('Property', SqlType.text()),
        ('AccountNumber', SqlType.text()),
        ('AccountName', SqlType.text()),
        ('Name', SqlType.text()),
        ('Tags', SqlType.text()),
        ('OriginalCharge', SqlType.double()),
        ('OriginalChargeDate', SqlType.date()),
        ('TotalOutstandingBalance', SqlType.text()),
        ('Month0', SqlType.double()),
        ('Month1', SqlType.double()),
        ('Month2', SqlType.double()),
        ('Month3', SqlType.double()),
        ('Month4', SqlType.double()),
        ('Month5', SqlType.double()),
        ('Month6', SqlType.double()),
        ('Month7', SqlType.double()),
        ('Month8', SqlType.double()),
        ('Month9', SqlType.double()),
        ('Month10', SqlType.double()),
        ('Month11', SqlType.double()),
        ('TxnId', SqlType.int()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('GlAccountId', SqlType.text()),
        ('TenantId', SqlType.text()),
        ('OccupancyId', SqlType.text()),
    ],

    'leasing_agent_performance': [

        ('AssignedUser', SqlType.text()),
        ('GuestCards', SqlType.int()),
        ('Showings', SqlType.int()),
        ('Applications', SqlType.int()),
        ('LeasedUnits', SqlType.int()),
        ('AssignedUserID', SqlType.int()),
    ],

    'owner_directory': [

        ('Name', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('Email', SqlType.text()),
        ('AlternativePayee', SqlType.text()),
        ('PaymentType', SqlType.text()),
        ('LastPaymentDate', SqlType.text()),
        ('HoldPayments', SqlType.text()),# confusion
        ('OwnerPacketReports', SqlType.text()),
        ('SendOwnerPacketsByEmail', SqlType.text()),#confusion
        ('PropertiesOwned', SqlType.text()),
        ('Tags', SqlType.text()),
        ('OwnerAddress', SqlType.text()),
        ('LastPacketSent', SqlType.text()),
        ('OwnerStreet1', SqlType.text()),
        ('OwnerStreet2', SqlType.text()),
        ('OwnerCity', SqlType.text()),
        ('OwnerState', SqlType.text()),
        ('OwnerZip', SqlType.text()),
        ('OwnerCountry', SqlType.text()),
        ('OwnerId', SqlType.text()),
        ('PropertiesOwnedIDs', SqlType.text()),
        ('NotesForTheOwner', SqlType.text()),
        ('FirstName', SqlType.text()),
        ('LastName', SqlType.text()),

    ],
    'property_budget': [

        ('GlAccountName', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('Year', SqlType.text()),
        ('Jan', SqlType.double()),
        ('Feb', SqlType.double()),
        ('Mar', SqlType.double()),
        ('Apr', SqlType.double()),
        ('May', SqlType.double()),
        ('Jun', SqlType.double()),
        ('Jul', SqlType.double()),
        ('Aug', SqlType.double()),
        ('Sep', SqlType.double()),
        ('Oct', SqlType.double()),
        ('Nov', SqlType.double()),
        ('Dec', SqlType.double()),
        ('Notes', SqlType.text()),
        ('GlAccountId', SqlType.int()),
        ('PropertyId', SqlType.int()),

        ],
    'property_directory': [

        ('Property', SqlType.text()),
        ('MarketRent', SqlType.double()),
        ('Units', SqlType.int()),
        ('SqFt', SqlType.int()),
        ('ManagementFlatFee', SqlType.double()),
        ('ManagementFeePercent', SqlType.double()), #confusion
        ('MinimumFee', SqlType.double()),
        ('Reserve', SqlType.double()),

        ('HomeWarrantyExpiration', SqlType.date()),
        ('InsuranceExpiration', SqlType.date()),
        ('TaxYearEnd', SqlType.int()),
        ('Owners', SqlType.text()),

        ('Description', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('TaxAuthority', SqlType.text()),
        ('PayerName', SqlType.text()),
        ('Portfolio', SqlType.text()),
        ('PremiumLeadsStatus', SqlType.text()),
        ('PremiumLeadsMonthlyCap', SqlType.double()),
        ('PremiumLeadsActivationDate', SqlType.date()),
        ('OwnerIDs', SqlType.text()),
        ('PropertyGroupId', SqlType.text()),

        ('Visibility', SqlType.text()),
        ('MaintenanceLimit', SqlType.double()),

        ('MaintenanceNotes', SqlType.text()),
        ('SiteManagerName', SqlType.text()),
        ('SiteManagerPhoneNumber', SqlType.text()),
        ('ManagementFeeType', SqlType.text()),
        ('LeaseFeeType', SqlType.double()),

        ('LeaseFlatFee', SqlType.text()),# confusion
        ('LeaseFeePercent', SqlType.text()),
        ('OwnerPaymentType', SqlType.text()),
        ('PropertyType', SqlType.text()),
        ('PropertyCreatedOn', SqlType.date()),
        ('PropertyCreatedBy', SqlType.text()),
        ('LateFeeType', SqlType.text()),
        ('LateFeeBaseAmount', SqlType.double()),
        ('LateFeeDailyAmount', SqlType.double()),

        ('LateFeeGracePeriod', SqlType.int()),
        ('LateFeeGracePeriodFixedDay', SqlType.int()),
        ('LateFeeGraceBalance', SqlType.double()),
        ('MaxDailyLateFeesAmount', SqlType.double()),

        ('IgnorePartialPayments', SqlType.text()),
        ('YearBuilt', SqlType.int()),
        ('ContractExpirations', SqlType.date()),
        ('ManagementStartDate', SqlType.date()),
        ('ManagementEndDate', SqlType.date()),

        ('ManagementEndReason', SqlType.text()),
        ('AgentOfRecord', SqlType.text()),
        ('PropertyClass', SqlType.text()),
        ('OnlineMaintenanceRequestInstructions', SqlType.text()),
        ('Amenities', SqlType.text()),

    ],

    'property_group_directory': [

        ('PropertyName', SqlType.text()),
        ('PropertyAddress', SqlType.text()),
        ('Property', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('PropertyLegacyStreet1', SqlType.text()),
        ('PropertyGroupName', SqlType.text()),
        ('Portfolio', SqlType.text()),
        ('PropertyGroupId', SqlType.int()),
        ('PortfolioId', SqlType.int()),

    ],

    'prospect_source_tracking': [

        ('Source', SqlType.text()),
        ('GuestCards', SqlType.int()),
        ('Showings', SqlType.int()),
        ('Applications', SqlType.int()),
        ('ApprovedApplications', SqlType.int()),
        ('ConvertedTenants', SqlType.int()),

    ],

    'purchase_order': [

        ('PurchaseOrderNumber', SqlType.text()),
        ('Property', SqlType.text()),
        ('Description', SqlType.text()),
        ('Account', SqlType.text()),
        ('UnitName', SqlType.text()),
        ('VendorName', SqlType.text()),
        ('ApprovalStatus', SqlType.text()),
        ('LastApprover', SqlType.text()),
        ('LastApprovedOn', SqlType.text()),
        ('CreatedAt', SqlType.date()),
        ('RequiredBy', SqlType.date()),

        ('Received', SqlType.text()),#confusion
        ('Completed', SqlType.text()),#confusion
        ('SumOfBills', SqlType.double()),
        ('Amount', SqlType.double()),

        ('AllBills', SqlType.text()),
        ('BilledAmount', SqlType.double()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('AccountName', SqlType.text()),
        ('AccountNumber', SqlType.text()),
        ('GlAccountId', SqlType.int()),

        ('ShippedTo', SqlType.text()),
        ('CreatedBy', SqlType.text()),
        ('UpdatedAt', SqlType.date()),
        ('Canceled', SqlType.text()),#confusion

        ('unit_id', SqlType.int()),
        ('PurchaseOrderId', SqlType.int()),

        ('Instructions', SqlType.text()),
        ('WorkOrders', SqlType.text()),
        ('RevisionInstructions', SqlType.text()),
        ('RevisionAssignee', SqlType.text()),
        ('RevisionRequester', SqlType.text()),
        ('RevisionRequestedDate', SqlType.text()),
        ('RevisionCompletedDate', SqlType.text()),
    ],

    'receivables_activity': [

        ('Property', SqlType.text()),
        ('Party', SqlType.text()),
        ('Status', SqlType.text()),
        ('TxnAmount', SqlType.double()),

        ('TxnRemarks', SqlType.text()),
        ('TxnReference', SqlType.text()),
        ('TxnReceiptDate', SqlType.date()),
        ('PortalActivated', SqlType.text()), # confusion

        ('LastOnlineReceiptDate', SqlType.date()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),

        ('OnlinePaymentsRecurringCount', SqlType.int()),
        ('OnlinePaymentsRecurringTotal', SqlType.text()),
        ('MoveIn', SqlType.date()),

        ('Emails', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),

        ('CertifiedFundsOnly', SqlType.text()), # confusion
        ('OptedOutOfPortal', SqlType.text()),# confusion

        ('PaymentType', SqlType.text()),
        ('MustPayBalanceInFull', SqlType.text()), # confusion
        ('PropertyList', SqlType.text()),
        ('OccupancyId', SqlType.int()),
        ('SelectedTenantId', SqlType.int()),
        ('UnitId', SqlType.int()),

    ],

    'rent_roll': [

        ('Unit', SqlType.text()),
        ('UnitTags', SqlType.text()),
        ('BdBa', SqlType.text()),
        ('Tenant', SqlType.text()),
        ('Status', SqlType.text()),

        ('SquareFt', SqlType.int()),
        ('MarketRent', SqlType.double()),
        ('Rent', SqlType.double()),
        ('Deposit', SqlType.double()),
        ('LeaseFrom', SqlType.date()),
        ('LeaseTo', SqlType.date()),
        ('MoveIn', SqlType.date()),
        ('MoveOut', SqlType.date()),

        ('PastDue', SqlType.double()),
        ('NSF', SqlType.int()),
        ('Late', SqlType.int()),
        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('PropertyType', SqlType.text()),

        ('OccupancyId', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('UnitType', SqlType.text()),
        ('StatusBySquareFeet', SqlType.text()),
        ('MonthlyMarketRentSquareFt', SqlType.text()),
        ('AnnualMarketRentSquareFt', SqlType.double()),
        ('MonthlyRentSquareFt', SqlType.double()),
        ('AnnualRentSquareFt', SqlType.double()),
        ('Amenities', SqlType.double()),

        ('AdditionalTenants', SqlType.text()),
        ('MonthlyCharges', SqlType.double()),
        ('RentReady', SqlType.text()),  #confusion

        ('RentStatus', SqlType.text()),
        ('LegalRent', SqlType.double()),
        ('LastRentIncrease', SqlType.date()),
        ('NextRentAdjustment', SqlType.date()),

        ('NextRentIncreaseAmount', SqlType.double()),
        ('NextRentIncrease', SqlType.date()),
        ('ApplicationFee', SqlType.double()),
        ('AmenitiesPrice', SqlType.double()),
        ('ComputedMarketRent', SqlType.double()),
        ('PropertyGroupId', SqlType.text()),
        ('PortfolioId', SqlType.int()),
        ('TenantTags', SqlType.text()),
        ('LeaseExpiresMonth', SqlType.text()),
        ('TenantId', SqlType.int()),
        ('AdditionalTenantIds', SqlType.text()),
        ('PreviousOccupancyRent', SqlType.double()),
        ('PreviousRent', SqlType.double()),

    ],

    'rent_roll_itemized': [

        ('Unit', SqlType.text()),
        ('BdBa', SqlType.text()),
        ('Status', SqlType.text()),

        ('SquareFt', SqlType.int()),

        ('GL0', SqlType.double()),
        ('GL1', SqlType.double()),
        ('GL2', SqlType.double()),
        ('GL3', SqlType.double()),
        ('GL4', SqlType.double()),
        ('GL5', SqlType.double()),
        ('GL6', SqlType.double()),
        ('GL7', SqlType.double()),
        ('GL8', SqlType.double()),
        ('GL9', SqlType.double()),
        ('GL10', SqlType.double()),
        ('GL11', SqlType.double()),
        ('GL12', SqlType.double()),
        ('GL13', SqlType.double()),
        ('GL14', SqlType.double()),
        ('GL15', SqlType.double()),
        ('GL16', SqlType.double()),
        ('GL17', SqlType.double()),
        ('GL18', SqlType.double()),
        ('GL19', SqlType.double()),
        ('GL20', SqlType.double()),
        ('GL21', SqlType.double()),
        ('GL22', SqlType.double()),
        ('GL23', SqlType.double()),
        ('GL24', SqlType.double()),
        ('GL25', SqlType.double()),
        ('GL26', SqlType.double()),
        ('GL27', SqlType.double()),
        ('GL28', SqlType.double()),
        ('GL29', SqlType.double()),
        ('GL30', SqlType.double()),
        ('GL31', SqlType.double()),
        ('GL32', SqlType.double()),
        ('GL33', SqlType.double()),
        ('GL34', SqlType.double()),
        ('Total', SqlType.double()),
        ('OtherCharges', SqlType.double()),

        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('PropertyType', SqlType.text()),

        ('OccupancyId', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('UnitTags', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('Tenant', SqlType.text()),

        ('MarketRent', SqlType.double()),
        ('ComputedMarketRent', SqlType.double()),
        ('MonthlyRentSquareFt', SqlType.double()),
        ('AnnualRentSquareFt', SqlType.double()),
        ('Deposit', SqlType.double()),

        ('LeaseFrom', SqlType.date()),
        ('LeaseTo', SqlType.date()),
        ('LastRentIncrease', SqlType.date()),
        ('NextRentAdjustment', SqlType.text()),

        ('NextRentIncreaseAmount', SqlType.double()),
        ('NextRentIncrease', SqlType.date()),
        ('MoveIn', SqlType.date()),
        ('MoveOut', SqlType.date()),

        ('PastDue', SqlType.double()),
        ('NSF', SqlType.int()),
        ('Late', SqlType.int()),
        ('Amenities', SqlType.text()),
        ('AdditionalTenants', SqlType.text()),

        ('MonthlyCharges', SqlType.double()),
        ('RentReady', SqlType.text()),  # confusion
        ('RentStatus', SqlType.text()),
        ('LegalRent', SqlType.double()),
        ('TenantTags', SqlType.text()),
        ('PropertyGroupId', SqlType.text()),
        ('PortfolioId', SqlType.int()),

    ],

    'rentable_items': [
        ('RentableItemName', SqlType.text()),
        ('GLAccount', SqlType.text()),
        ('Amount', SqlType.double()),
        ('Tenant', SqlType.text()),
        ('Available', SqlType.text()),  # confusion
        ('Type', SqlType.text()),
        ('Description', SqlType.text()),
        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),

        ('StartDate', SqlType.date()),
        ('EndDate', SqlType.date()),
        ('Unit', SqlType.text()),
        ('OccupancyId', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('GLAccountId', SqlType.int()),
        ('LicensePlates', SqlType.text()),

    ],
    'rental_applications': [
        ('Applicants', SqlType.text()),
        ('Received', SqlType.date()),
        ('DesiredMoveIn', SqlType.date()),
        ('LeadSource', SqlType.text()),
        ('Status', SqlType.text()),
        ('Screening', SqlType.text()),
        ('AssignedUserId', SqlType.int()),

        ('CreatedBy', SqlType.text()),
        ('ReasonForStatus', SqlType.text()),
        ('UnitTitle', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('UnitName', SqlType.text()),
        ('CampaignTitle', SqlType.text()),
        ('ApplyingFor', SqlType.text()),
        ('AssignedUser', SqlType.text()),
        ('ApplicantReportedSource', SqlType.text()),

        ('ApprovedAt', SqlType.date()),
        ('DeniedAt', SqlType.date()),
        ('CanceledAt', SqlType.date()),

        ('ApplicationFeePaid', SqlType.text()),#confusion
        ('RentalApplicationId', SqlType.int()),
        ('RentalApplicationGroupId', SqlType.int()),
        ('Email', SqlType.text()),
        ('PhoneNumber', SqlType.text()),
        ('CurrentAddress1', SqlType.text()),
        ('CurrentAddress2', SqlType.text()),
        ('CurrentCity', SqlType.text()),
        ('CurrentState', SqlType.text()),
        ('CurrentZip', SqlType.text()),
        ('CurrentMonthlyRent', SqlType.text()),
        ('ResidedFrom', SqlType.date()),
        ('ResidedTo', SqlType.date()),
        ('LandlordName', SqlType.text()),
        ('LandlordPhoneNumber', SqlType.text()),
        ('LandlordEmail', SqlType.text()),
        ('Previous1Address1', SqlType.text()),
        ('Previous1Address2', SqlType.text()),
        ('PreviousCity1', SqlType.text()),
        ('PreviousState1', SqlType.text()),
        ('PreviousZip1', SqlType.text()),
        ('PreviousMonthlyRent1', SqlType.text()),

        ('PreviousResidedFrom1', SqlType.date()),
        ('PreviousResidedTo1', SqlType.date()),
        ('PreviousLandlordName1', SqlType.text()),
        ('PreviousLandlordPhoneNumber1', SqlType.text()),
        ('PreviousLandlordEmail1', SqlType.text()),
        ('Previous2Address1', SqlType.text()),
        ('Previous2Address2', SqlType.text()),
        ('PreviousCity2', SqlType.text()),
        ('PreviousState2', SqlType.text()),
        ('PreviousZip2', SqlType.text()),
        ('PreviousMonthlyRent2', SqlType.text()),
        ('PreviousResidedFrom2', SqlType.date()),
        ('PreviousResidedTo2', SqlType.date()),
        ('PreviousLandlordName2', SqlType.text()),
        ('PreviousLandlordPhoneNumber2', SqlType.text()),
        ('PreviousLandlordEmail2', SqlType.text()),
        ('EmployerName', SqlType.text()),
        ('EmployerPhoneNumber', SqlType.text()),
        ('MonthlySalary', SqlType.text()),
        ('PositionHeld', SqlType.text()),
        ('YearsWorked', SqlType.text()),
        ('AdditionalIncomes', SqlType.text()),
        ('PetsNames', SqlType.text()),
        ('PetsKinds', SqlType.text()),
        ('PetsWeights', SqlType.text()),
        ('UnitAddress', SqlType.text()),
        ('UnitStreet1', SqlType.text()),
        ('UnitStreet2', SqlType.text()),
        ('UnitCity', SqlType.text()),
        ('UnitState', SqlType.text()),
        ('UnitZip', SqlType.text()),
        ('UnitId', SqlType.int()),
        ('PropertyId', SqlType.int()),
        ('TenantId', SqlType.int()),

    ],

    'screening_decisions': [

        ('ApplicantName', SqlType.text()),
        ('ScreeningDecision', SqlType.text()),
        ('ScreeningTimestamp', SqlType.date()),
        ('FinalDecision', SqlType.text()),
        ('OverrideReasons', SqlType.text()),
        ('OverrideComment', SqlType.text()),
        ('OverrideTimestamp', SqlType.date()),
        ('OverrideUser', SqlType.text()),
        ('RentalApplicationId', SqlType.int()),

        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),

    ],
    'tenant_debt_collections_status': [
        ('Tenants', SqlType.text()),
        ('Unit', SqlType.text()),
        ('Property', SqlType.text()),
        ('VendorAccountNumber', SqlType.text()),
        ('SubmissionDate', SqlType.date()),
        ('LastPaymentDate', SqlType.double()),
        ('BalancePlaced', SqlType.double()),
        ('AmountCollected', SqlType.double()),

        ('BalanceDue', SqlType.text()),
        ('StatusDescription', SqlType.text()),

        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),

        ('PropertyZip', SqlType.text()),
        ('BalanceCancelled', SqlType.double()),
        ('CancellationDate', SqlType.date()),
        ('OccupancyId', SqlType.int()),
        ('UnitId', SqlType.int()),

    ],
    'surveys_summary': [

        ('Tenant', SqlType.text()),
        ('Property', SqlType.text()),
        ('Question1', SqlType.text()),
        ('Question2', SqlType.text()),
        ('Question3', SqlType.text()),
        ('Question4', SqlType.text()),
        ('DateSent', SqlType.date()),
        ('DateReceived', SqlType.date()),
        ('SurveyId', SqlType.text()),
        ('SurveyType', SqlType.text()),
        ('PropertyId', SqlType.text()),
    ],

    'tenant_directory': [

        ('Property', SqlType.text()),
        ('Unit', SqlType.text()),
        ('Tenant', SqlType.text()),
        ('Status', SqlType.text()),
        ('TenantType', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('Emails', SqlType.text()),

        ('MoveIn', SqlType.date()),
        ('LeaseTo', SqlType.date()),

        ('Rent', SqlType.double()),
        ('Deposit', SqlType.double()),

        ('TenantTags', SqlType.text()),
        ('TenantAddress', SqlType.text()),
        ('TenantStreet1', SqlType.text()),
        ('TenantStreet2', SqlType.text()),
        ('TenantCity', SqlType.text()),
        ('TenantState', SqlType.text()),
        ('TenantZip', SqlType.text()),
        ('TenantBirthdate', SqlType.text()),
        ('PropertyName', SqlType.text()),

        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('CertifiedFundsOnly', SqlType.text()), #confusion

        ('LeaseFrom', SqlType.date()),
        ('LastLeaseRenewal', SqlType.date()),
        ('MoveOut', SqlType.date()),
        ('NextRentIncrease', SqlType.date()),
        ('LastRentIncrease', SqlType.date()),
        ('NextRentAdjustment', SqlType.date()),

        ('TenantPortalActivated', SqlType.text()),#Confusion

        ('OnlinePaymentsRecurringTotal', SqlType.text()),
        ('OnlinePaymentsRecurringCount', SqlType.int()),

        ('TenantPortalLogin', SqlType.text()),
        ('SendRentReminders', SqlType.text()),#Confusion

        ('UnitTags', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('LateFeeType', SqlType.text()),

        ('LateFeeBaseAmount', SqlType.double()),
        ('LateFeeDailyAmount', SqlType.double()),

        ('RentGraceDays', SqlType.int()),
        ('RentGraceDayFixedDay', SqlType.int()),
        ('LateFeeGraceBalance', SqlType.double()),
        ('MaxDailyLateFeesAmount', SqlType.date()),

        ('IgnorePartialPayments', SqlType.text()),
        ('InsuranceCompanyName', SqlType.text()),
        ('InsuranceExpiration', SqlType.date()),
        ('InsurancePolicyNumber', SqlType.text()),
        ('TransactionFee', SqlType.text()),
        ('PrimaryTenant', SqlType.text()),#confusion
        ('FirstName', SqlType.text()),
        ('LastName', SqlType.text()),
        ('LicensePlates', SqlType.text()),
        ('Pets', SqlType.text()),
        ('AutoNsfFeeAmount', SqlType.double()),
        ('RequireOnlinePaymentsInFull', SqlType.text()),#confusion
        ('OccupancyId', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('SelectedTenantId', SqlType.int()),
        ('GuestCardId', SqlType.int()),
        ('RentalApplicationId', SqlType.int()),
        ('PortfolioId', SqlType.int()),

    ],

    'tenant_vehicle_info': [

        ('Property', SqlType.text()),
        ('Unit', SqlType.text()),
        ('Tenant', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('TenantStatus', SqlType.text()),
        ('Make', SqlType.text()),
        ('Model', SqlType.text()),
        ('Color', SqlType.text()),
        ('LicensePlate', SqlType.text()),
        ('Year', SqlType.text()),
        ('PermitNumber', SqlType.text()),
        ('UnitId', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('OccupancyId', SqlType.int()),
        ('TenantId', SqlType.int()),
        ('RentableItem', SqlType.text()),

    ],
    'trial_balance': [
        ('AccountName', SqlType.text()),
        ('BalanceForward', SqlType.double()),
        ('Debit', SqlType.double()),
        ('Credit', SqlType.double()),
        ('EndingBalance', SqlType.double()),
    ],
    'trust_account_balance': [
        ('Property', SqlType.text()),
        ('CashBalance', SqlType.double()),
        ('EscrowBalance', SqlType.double()),
        ('DepositBalance', SqlType.double()),
        ('AdditionalDeposits', SqlType.double()),

        ('Owner', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('OwnerIDs', SqlType.text()),

        ('UnitDeposits', SqlType.double()),
        ('UnpaidBillsAmount', SqlType.double()),
        ('UnusedPrepaymentAmount', SqlType.double()),
        ('OperatingBankAccount', SqlType.text()),
        ('ReserveAmount', SqlType.double()),
        ('WorkOrderEstimates', SqlType.double()),

    ],

    'tenant_tickler': [
        ('OccurredDate', SqlType.date()),
        ('Event', SqlType.text()),
        ('Property', SqlType.text()),
        ('Unit', SqlType.text()),
        ('UnitTags', SqlType.text()),
        ('Tenant', SqlType.text()),
        ('TenantPhoneNumber', SqlType.text()),
        ('TenantEmail', SqlType.text()),
        ('Rent', SqlType.double()),
        ('LeaseFrom', SqlType.date()),
        ('LeaseTo', SqlType.date()),

        ('Deposit', SqlType.double()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('TenantTags', SqlType.text()),
        ('MoveOutDate', SqlType.date()),
        ('MoveOutReason', SqlType.text()),
        ('MoveInDate', SqlType.date()),
        ('LeaseSignDate', SqlType.date()),
        ('AssignedUser', SqlType.text()),
        ('TenantStatus', SqlType.text()),
        ('UnitId', SqlType.int()),
        ('OccupancyId', SqlType.int()),
        ('TenantId', SqlType.int()),
        ('RentalApplicationId', SqlType.int()),
        ('PortfolioId', SqlType.int()),
    ],

    'unit_inspection': [

        ('UnitName', SqlType.text()),
        ('LastInspectionDate', SqlType.date()),
        ('TenantName', SqlType.text()),
        ('TenantPrimaryPhoneNumber', SqlType.text()),
        ('MoveInDate', SqlType.date()),
        ('MoveOutDate', SqlType.date()),

        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),

        ('UnitId', SqlType.int()),
        ('OccupancyId', SqlType.int()),
        ('Rentable', SqlType.text()), # confusion
        ('UnitTags', SqlType.text()),

    ],

    'unit_directory': [

        ('UnitName', SqlType.text()),
        ('MarketRent', SqlType.double()),
        ('DefaultDeposit', SqlType.double()),
        ('SquareFt', SqlType.int()),
        ('Bedrooms', SqlType.int()),

        ('Bathrooms', SqlType.double()),
        ('UnitTags', SqlType.text()),
        ('Rentable', SqlType.text()),# confusion

        ('Description', SqlType.text()),
        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('UnitAddress', SqlType.text()),
        ('UnitStreet1', SqlType.text()),
        ('UnitStreet2', SqlType.text()),
        ('UnitCity', SqlType.text()),
        ('UnitState', SqlType.text()),
        ('UnitZip', SqlType.text()),
        ('MarketingTitle', SqlType.text()),
        ('MarketingDescription', SqlType.text()),
        ('AdvertisedRent', SqlType.double()),

        ('PostedToWebsite', SqlType.text()), # confusion
        ('PostedToInternet', SqlType.text()), # confusion

        ('YouTubeURL', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('CreatedOn', SqlType.date()),

        ('RubsEnabled', SqlType.text()),
        ('RubsEnabledOn', SqlType.text()),# confusion

        ('RentStatus', SqlType.date()),
        ('LegalRent', SqlType.text()),
        ('ApplicationFee', SqlType.double()),
        ('RentReady', SqlType.double()),# confusion

        ('RentDueDay', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('ComputedMarketRent', SqlType.double()),
        ('ReadyForShowingOn', SqlType.date()),
        ('Visibility', SqlType.text()),
        ('RentableUid', SqlType.text()),
    ],

    'unit_turn_detail': [

        ('Property', SqlType.text()),
        ('Unit', SqlType.text()),
        ('UnitTurnId', SqlType.text()),
        ('Notes', SqlType.text()),
        ('ReferenceUser', SqlType.text()),
        ('MoveOutDate', SqlType.date()),
        ('TurnEndDate', SqlType.date()),

        ('TargetDaysToComplete', SqlType.int()),
        ('TotalDaysToComplete', SqlType.int()),
        ('LaborFromWorkOrders', SqlType.double()),
        ('PurchaseOrdersFromWorkOrders', SqlType.double()),
        ('BillablesFromWorkOrders', SqlType.double()),
        ('InventoryFromWorkOrders', SqlType.double()),

        ('TotalBilled', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('UnitId', SqlType.int()),
    ],

    'unit_vacancy': [

        ('Unit', SqlType.text()),
        ('UnitTags', SqlType.text()),
        ('BedAndBath', SqlType.text()),
        ('SqFt', SqlType.int()),
        ('UnitStatus', SqlType.text()),
        ('RentReady', SqlType.text()),
        ('DaysVacant', SqlType.int()),

        ('LastRent', SqlType.double()),
        ('SchdRent', SqlType.double()),
        ('NewRent', SqlType.double()),
        ('LastMoveIn', SqlType.date()),
        ('LastMoveOut', SqlType.date()),
        ('AvailableOn', SqlType.date()),
        ('NextMoveIn', SqlType.date()),

        ('Description', SqlType.text()),
        ('AdvertisedRent', SqlType.double()),

        ('PostedToWebsite', SqlType.text()),#confusion
        ('PostedToInternet', SqlType.text()),#confusion

        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('Amenities', SqlType.text()),
        ('Address', SqlType.text()),
        ('UnitStreet1', SqlType.text()),
        ('UnitStreet2', SqlType.text()),
        ('UnitCity', SqlType.text()),
        ('UnitState', SqlType.text()),
        ('UnitZip', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('AmenitiesPrice', SqlType.double()),
        ('ComputedMarketRent', SqlType.double()),
        ('ReadyForShowingOn', SqlType.date()),
        ('PropertyId', SqlType.date()),
        ('UnitId', SqlType.int()),

    ],

    'upcoming_activities': [

        ('ActivityDate', SqlType.date()),
        ('Activity', SqlType.text()),
        ('ActivityFor', SqlType.text()),
        ('Label', SqlType.text()),
        ('Property', SqlType.text()),
        ('AssignedUser', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),

        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('UnitAddress', SqlType.text()),
        ('UnitStreet', SqlType.text()),
        ('UnitStreet2', SqlType.text()),
        ('UnitCity', SqlType.text()),
        ('UnitState', SqlType.text()),
        ('UnitZip', SqlType.text()),
        ('CreatedBy', SqlType.text()),
        ('CompletedBy', SqlType.text()),
        ('LastEditedBy', SqlType.text()),

        ('CreatedOn', SqlType.date()),
        ('CompletedOn', SqlType.date()),
        ('LastEditedOn', SqlType.date()),
        ('Status', SqlType.text()),
        ('UnitId', SqlType.text()),
        ('OccupancyId', SqlType.text()),
        ('OwnerId', SqlType.text()),
    ],

    'vendor_directory': [

        ('CompanyName', SqlType.text()),
        ('Name', SqlType.text()),
        ('VendorAddress', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('Email', SqlType.text()),
        ('DefaultGLAccount', SqlType.text()),
        ('PaymentType', SqlType.text()),
        ('Send1099', SqlType.text()), # confusion


        ('WorkersCompExpires', SqlType.date()),
        ('LiabilityInsExpires', SqlType.date()),
        ('EPACertExpires', SqlType.date()),
        ('AutoInsExpires', SqlType.date()),
        ('StateLicExpires', SqlType.date()),
        ('ContractExpires', SqlType.date()),

        ('Tags', SqlType.text()),
        ('VendorStreet1', SqlType.text()),
        ('VendorStreet2', SqlType.text()),
        ('VendorCity', SqlType.text()),
        ('VendorState', SqlType.text()),
        ('VendorZip', SqlType.text()),
        ('VendorId', SqlType.int()),

        ('VendorTrades', SqlType.text()),
        ('DoNotUseForWorkOrder', SqlType.text()), # confusion
        ('Terms', SqlType.text()),
        ('FirstName', SqlType.text()),
        ('LastName', SqlType.text()),
    ],

    'work_order': [

        ('Property', SqlType.text()),
        ('Priority', SqlType.text()),
        ('WorkOrderType', SqlType.text()),
        ('HomeWarrantyExpiration', SqlType.date()),

        ('WorkOrderNumber', SqlType.text()),
        ('JobDescription', SqlType.text()),
        ('Instructions', SqlType.text()),
        ('Status', SqlType.text()),
        ('Vendor', SqlType.text()),
        ('UnitName', SqlType.text()),
        ('PrimaryTenant', SqlType.text()),
        ('CreatedAt', SqlType.date()),

        ('EstimateReqOn', SqlType.date()),
        ('EstimatedOn', SqlType.date()),

        ('EstimateAmount', SqlType.double()),
        ('ScheduledStart', SqlType.text()),
        ('ScheduledEnd', SqlType.date()),

        ('WorkCompletedOn', SqlType.date()),
        ('CompletedOn', SqlType.date()),

        ('Amount', SqlType.double()),
        ('Invoice', SqlType.text()),
        ('Recurring', SqlType.text()), # confusion

        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('UnitAddress', SqlType.text()),
        ('UnitStreet', SqlType.text()),
        ('UnitStreet2', SqlType.text()),
        ('UnitCity', SqlType.text()),
        ('UnitState', SqlType.text()),
        ('UnitZip', SqlType.text()),
        ('ServiceRequestNumber', SqlType.text()),
        ('ServiceRequestDescription', SqlType.text()),

        ('vendor_id', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('OccupancyId', SqlType.int()),

        ('PrimaryTenantEmail', SqlType.text()),
        ('PrimaryTenantPhoneNumber', SqlType.text()),
        ('CreatedBy', SqlType.text()),
        ('AssignedUser', SqlType.text()),

        ('LastBilledOn', SqlType.date()),
        ('CanceledOn', SqlType.date()),

        ('WorkOrderId', SqlType.text()),
        ('ServiceRequestId', SqlType.text()),

        ('SubmittedByTenant', SqlType.text()),# confusion
        ('RequestingTenant', SqlType.text()),
        ('MaintenanceLimit', SqlType.text()),
        ('StatusNotes', SqlType.text()),
        ('FollowUpOn', SqlType.date()),
        ('VendorTrade', SqlType.text()),
    ],

}
