from tableauhyperapi import SqlType

data = {
    'tenant_directory': [
        ('TenantAddress', SqlType.text()),
        ('TenantStreet', SqlType.text()),
        ('TenantStreet2', SqlType.text()),
        ('TenantCity', SqlType.text()),
        ('TenantState', SqlType.text()),
        ('TenantZip', SqlType.text()),
        ('TenantBirthdate', SqlType.date()),
        ('Property', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.int()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('Unit', SqlType.text()),
        ('Tenant', SqlType.text()),
        ('Status', SqlType.text()),
        ('TenantType', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('Emails', SqlType.text()),
        ('MoveIn', SqlType.date()),
        ('LeaseTo', SqlType.date()),
        ('Rent', SqlType.double()),
        ('Deposit', SqlType.double()),
        ('TenantTags', SqlType.text()),
        ('CertifiedFundsOnly', SqlType.text()),
        ('LeaseFrom', SqlType.date()),
        ('LastLeaseRenewal', SqlType.date()),
        ('MoveOut', SqlType.date()),
        ('NextRentIncrease', SqlType.date()),
        ('LastRentIncrease', SqlType.date()),
        ('NextRentAdjustment', SqlType.date()),
        ('TenantPortalActivated', SqlType.text()),
        ('OnlinePaymentsRecurringTotal', SqlType.text()),
        ('OnlinePaymentsRecurringCount', SqlType.int()),
        ('TenantPortalLogin', SqlType.text()),
        ('SendRentReminders', SqlType.text()),
        ('UnitTags', SqlType.text()),
        ('UnitType', SqlType.text()),
        ('LateFeeType', SqlType.text()),
        ('LateFeeBaseAmount', SqlType.double()),
        ('LateFeeDailyAmount', SqlType.double()),
        ('RentGraceDays', SqlType.int()),
        ('LateFeeGraceBalance', SqlType.double()),
        ('AISEnabled', SqlType.text()),
        ('InsuranceCompanyName', SqlType.text()),
        ('InsuranceExpiration', SqlType.date()),
        ('InsurancePolicyNumber', SqlType.text()),
        ('ConvenienceFee', SqlType.double()),
        ('PrimaryTenant', SqlType.text()),
        ('LicensePlates', SqlType.text()),
        ('Pets', SqlType.text()),
        ('occupancy_id', SqlType.int()),
        ('unit_id', SqlType.int()),
        ('SelectedTenantId', SqlType.int()),
        ('TenantStreet1', SqlType.text()),
        ('PropertyStreet1', SqlType.text()),
        ('RentGraceDayFixedDay', SqlType.int()),
        ('MaxDailyLateFeesAmount', SqlType.double()),
        ('IgnorePartialPayments', SqlType.text()),
        ('TransactionFee', SqlType.text()),
        ('FirstName', SqlType.text()),
        ('LastName', SqlType.text()),
        ('AutoNsfFeeAmount', SqlType.double()),
        # ('RequireOnlinePaymentsInFull', SqlType.double()), confustion
        ('OccupancyId', SqlType.int()),
        ('UnitId', SqlType.int()),
        ('GuestCardId', SqlType.int()),
        ('RentalApplicationId', SqlType.int()),
        ('PortfolioId', SqlType.int()),


    ],
}