from tableauhyperapi import SqlType

data = {
    'vendor_directory': [
        ('CompanyName', SqlType.text()),
        ('Name', SqlType.text()),
        ('Address', SqlType.text()),
        ('Street', SqlType.text()),
        ('Street2', SqlType.text()),
        ('City', SqlType.text()),
        ('State', SqlType.text()),
        ('Zip', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('Email', SqlType.text()),
        ('DefaultGLAccount', SqlType.text()),
        ('PaymentType', SqlType.text()),
        ('Send1099', SqlType.text()),
        ('WorkersCompExpires', SqlType.date()),
        ('LiabilityInsExpires', SqlType.date()),
        ('EPACertExpires', SqlType.date()),
        ('AutoInsExpires', SqlType.date()),
        ('Tags', SqlType.text()),
        ('vendor_id', SqlType.int()),
        ('VendorAddress', SqlType.text()),
        ('StateLicExpires', SqlType.date()),
        ('ContractExpires', SqlType.date()),
        ('VendorStreet1', SqlType.text()),
        ('VendorStreet2', SqlType.text()),
        ('VendorCity', SqlType.text()),
        ('VendorState', SqlType.text()),
        ('VendorZip', SqlType.text()),
        ('VendorId', SqlType.int()),
        ('VendorTrades', SqlType.text()),
        # ('DoNotUseForWorkOrder', SqlType.text()), confusion
        ('Terms', SqlType.text()),
        ('FirstName', SqlType.text()),
        ('LastName', SqlType.text()),
    ],

}