from tableauhyperapi import SqlType

data = {
    'payment_plans': [
        ('Property', SqlType.text()),
        ('AccountNumber', SqlType.text()),
        ('AccountName', SqlType.text()),
        ('Name', SqlType.text()),
        ('Tags', SqlType.text()),
        ('OriginalCharge', SqlType.text()),
        ('OriginalChargeDate', SqlType.text()),
        ('TotalOutstandingBalance', SqlType.text()),
        ('Month0', SqlType.text()),
        ('Month1', SqlType.text()),
        ('Month2', SqlType.text()),
        ('Month3', SqlType.text()),
        ('Month4', SqlType.text()),
        ('Month5', SqlType.text()),
        ('Month6', SqlType.text()),
        ('Month7', SqlType.text()),
        ('Month8', SqlType.text()),
        ('Month9', SqlType.text()),
        ('Month10', SqlType.text()),
        ('Month11', SqlType.text()),
        ('TxnId', SqlType.text()),
        ('PropertyName', SqlType.text()),
        ('PropertyId', SqlType.text()),
        ('PropertyAddress', SqlType.text()),
        ('PropertyStreet', SqlType.text()),
        ('PropertyStreet2', SqlType.text()),
        ('PropertyCity', SqlType.text()),
        ('PropertyState', SqlType.text()),
        ('PropertyZip', SqlType.text()),
        ('GlAccountId', SqlType.text()),
        ('TenantId', SqlType.text()),
        ('OccupancyId', SqlType.text()),
    ],

    'leasing_agent_performance': [

        ('AssignedUser', SqlType.text()),
        ('GuestCards', SqlType.text()),
        ('Showings', SqlType.text()),
        ('Applications', SqlType.text()),
        ('LeasedUnits', SqlType.text()),
        ('AssignedUserID', SqlType.text()),
    ],

    'owner_directory': [

        ('Name', SqlType.text()),
        ('PhoneNumbers', SqlType.text()),
        ('Email', SqlType.text()),
        ('AlternativePayee', SqlType.text()),
        ('PaymentType', SqlType.text()),
        ('LastPaymentDate', SqlType.text()),
        ('HoldPayments', SqlType.text()),
        ('OwnerPacketReports', SqlType.text()),
        ('SendOwnerPacketsByEmail', SqlType.text()),
        ('PropertiesOwned', SqlType.text()),
        ('Tags', SqlType.text()),
        ('OwnerAddress', SqlType.text()),
        ('LastPacketSent', SqlType.text()),
        ('OwnerStreet1', SqlType.text()),
        ('OwnerStreet2', SqlType.text()),
        ('OwnerCity', SqlType.text()),
        ('OwnerState', SqlType.text()),
        ('OwnerZip', SqlType.text()),
        ('OwnerCountry', SqlType.text()),
        ('OwnerId', SqlType.text()),
        ('PropertiesOwnedIDs', SqlType.text()),
        ('NotesForTheOwner', SqlType.text()),
        ('FirstName', SqlType.text()),
        ('LastName', SqlType.text()),

    ],

}
